### PR TITLE
some junk added

### PR DESCRIPTION
**Pull request by balamurugana**
adding some comment

### CODE REVIEW

**Comment by balamurugana** [comment]
its not a valid PR

**Comment by balamurugana** [comment]
adding a comment from python test program

**Comment by balamurugana** [comment]
is it issue comment?

**Comment by balamurugana** [comment]
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

**Comment by balamurugana** [comment]
```diff
+ this will be highlighted in green
```

**Comment by kmkanagaraj** [comment]
<div class="highlight highlight-source-diff"><pre><span class="pl-mdr">@@          Coverage Diff           @@</span>
<span class="pl-c"><span class="pl-c">#</span>#           master   #5351   +/-   ##</span>
======================================
  Coverage    62.4%   62.4%           
======================================
  Files         201     201           
  Lines       31114   31114           
======================================
  Hits        19418   19418           
  Misses      10256   10256           
  Partials     1440    1440</pre></div>

**Pull request closed without merging**
